In [9]:
import pandas as pd

# Load the Excel file
df = pd.read_excel("Thematic_Analysis_Final.xlsx")

# Metadata columns
metadata_cols = [
    'S2 - Topic Disussed', 'Topic Quote', 'Topic Important',
    'Quote Number', 'Participant Number', 'Category - L1', 'Sub Category - L2'
]

# One-hot columns start from column 8 (index 7)
one_hot_cols = df.columns[7:]

# --- View shape ---
print("DataFrame shape:", df.shape)

# --- View head ---
print("\nDataFrame head:")
print(df.head())

# --- Duplicate check for Topic Quote ---
duplicate_quotes = df[df['Topic Quote'].duplicated(keep=False)]

print("\nNumber of duplicate Topic Quotes:", duplicate_quotes.shape[0])
print("\nDuplicate Quotes:")
print(duplicate_quotes[['Topic Quote', 'Quote Number', 'Participant Number']])

DataFrame shape: (186, 30)

DataFrame head:
                                         Topic Quote  Quote Number  \
0  But for a higher number, definitely we need a ...            43
1  But in decision making - clearly, I think it h...            44
2  For exceptions that a manual underwrite would ...            45
3  I feel like if AI is not a human being AI can'...            46
4  See, the underwriting process is a very comple...            47

   Participant Number Gender Location  Years of Experience  \
0                 5.0      M   Europe                 12.0
1                 1.0      M   Europe                  4.0
2                 4.0      F       US                 20.0
3                 2.0      F       US                 15.0
4                 8.0      M    India                 10.0

             Category - L1  Manual Intervention in Complex or High-Risk Cases  \
0  Human Oversight Control                                                1.0
1  Human Oversight Control                                                NaN
2  Human Oversight Control                                                1.0
3  Human Oversight Control                                                NaN
4  Human Oversight Control                                                1.0

   Collaboration between AI and Humans  \
0                                  NaN
1                                  1.0
2                                  NaN
3                                  1.0
4                                  NaN

   Model Accuracy, Validation, and Comprehensiveness"  ...  \
0                                                NaN   ...
1                                                NaN   ...
2                                                NaN   ...
3                                                NaN   ...
4                                                NaN   ...

   Validation and Justification of Decisions  Clarity and Specificity  \
0                                        NaN                      NaN
1                                        NaN                      NaN
2                                        NaN                      NaN
3                                        NaN                      NaN
4                                        NaN                      NaN

   Emphasis on Individualized Decision Making  Usefulness and Efficiency  \
0                                         NaN                        NaN
1                                         NaN                        NaN
2                                         NaN                        NaN
3                                         NaN                        NaN
4                                         NaN                        NaN

   Support in Complex or Borderline Case  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN

   Preference for Combined Text and Visuals  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

   Graphical Clarity and Ease of Interpretation  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN

   Textual Detail for Depth and Context  \
0                                   NaN
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN

   Interactive and Feedback-Enabled Systems  Scenario based explanations
0                                       NaN                          NaN
1                                       NaN                          NaN
2                                       NaN                          NaN
3                                       NaN                          NaN
4                                       NaN                          NaN

[5 rows x 30 columns]

Number of duplicate Topic Quotes: 0

Duplicate Quotes:
Empty DataFrame
Columns: [Topic Quote, Quote Number, Participant Number]
Index: []

In [10]:
# Remove exact duplicate quotes (case-sensitive) and overwrite df
df = df.drop_duplicates(subset=['Topic Quote'], keep='first').reset_index(drop=True)

print("Rows after removing duplicates:", df.shape[0])

Rows after removing duplicates: 186

In [11]:
# Basic stats
num_quotes = df.shape[0]
num_participants = df['Participant Number'].nunique()

# Frequency of main categories
category_counts = df['Category - L1'].value_counts()

# --- FIX: convert one-hot columns to numeric ---
df[one_hot_cols] = df[one_hot_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

# Count of 1s in one-hot columns
one_hot_counts = df[one_hot_cols].sum().sort_values(ascending=False)

# Quotes per participant
quotes_per_participant = df.groupby('Participant Number')['Quote Number'].count()

# Display results
print("Total quotes:", num_quotes)
print("Total participants:", num_participants)

print("\nCategory counts:\n", category_counts)

print("\nOne-hot column counts:\n", one_hot_counts)

print("\nQuotes per participant:\n", quotes_per_participant)

Total quotes: 186
Total participants: 10

Category counts:
 Category - L1
Risks & Concerns           31
Semi Factual               25
Factual Explaination       23
Actionability              22
Counterfactual             22
Technical Elements         20
Explanation Format         19
Human Oversight Control    14
Regulatory & Complaince    10
Name: count, dtype: int64

One-hot column counts:
 Clarity and Specificity                               33
Validation and Justification of Decisions             32
Usefulness and Efficiency                             32
Data Integrity and Security Concerns                  16
Collaboration between AI and Humans                   16
Emphasis on Individualized Decision Making            14
Scenario based explanations                           10
Preference for Combined Text and Visuals              10
Human Judgment, Communication, and Contextual Gaps     9
Support in Complex or Borderline Case                  9
Other                                                  8
Professional Confidence & Judgement                    8
Regulation as a Mandate                                7
Data sources and inputs                                7
Manual Intervention in Complex or High-Risk Cases      6
Error Detection & Improvement                          5
Interactive and Feedback-Enabled Systems               5
Model Accuracy, Validation, and Comprehensiveness"     4
Textual Detail for Depth and Context                   4
Operational alignment                                  3
Graphical Clarity and Ease of Interpretation           3
Compliance by design                                   2
Decision Logic and scoring mechanics                   2
dtype: int64

Quotes per participant:
 Participant Number
1.0     16
2.0     22
3.0     16
4.0     20
5.0     16
6.0     17
7.0     20
8.0     20
9.0     17
10.0    21
Name: Quote Number, dtype: int64

In [12]:
import pandas as pd

# Assuming df and one_hot_cols are already defined

# Convert one-hot columns to numeric if not already done
df[one_hot_cols] = df[one_hot_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

# Loop through each Category - L1
for category in df['Category - L1'].unique():
    # Filter rows for the category
    cat_df = df[df['Category - L1'] == category]
    
    # Sum one-hot columns for this category
    cat_one_hot_sum = cat_df[one_hot_cols].sum()
    
    # Keep only columns where sum > 0
    cat_one_hot_sum = cat_one_hot_sum[cat_one_hot_sum > 0]
    
    # Skip if no columns have values
    if cat_one_hot_sum.empty:
        continue
    
    # Convert to DataFrame
    cat_table = pd.DataFrame(cat_one_hot_sum).rename(columns={0: 'Count'})
    
    # Add total row
    total_row = pd.DataFrame(cat_table.sum()).T
    total_row.index = ['Total']
    cat_table = pd.concat([cat_table, total_row])
    
    # Display table
    print(f"\nCategory: {category}")
    display(cat_table)

Category: Human Oversight Control

                                                   Count
Manual Intervention in Complex or High-Risk Cases      6
Collaboration between AI and Humans                    8
Total                                                 14

Category: Risks & Concerns

                                                    Count
Model Accuracy, Validation, and Comprehensiveness"      4
Human Judgment, Communication, and Contextual Gaps      9
Data Integrity and Security Concerns                   16
Other                                                   4
Total                                                  33

Category: Technical Elements

                                      Count
Other                                     4
Data sources and inputs                   7
Professional Confidence & Judgement       2
Error Detection & Improvement             5
Decision Logic and scoring mechanics      2
Total                                    20

Category: Regulatory & Complaince

                         Count
Regulation as a Mandate      7
Compliance by design         2
Operational alignment        3
Total                       12

Category: Factual Explaination

                                           Count
Professional Confidence & Judgement            5
Validation and Justification of Decisions      9
Clarity and Specificity                       11
Usefulness and Efficiency                      5
Total                                         30

Category: Semi Factual

                                            Count
Clarity and Specificity                        15
Emphasis on Individualized Decision Making     10
Usefulness and Efficiency                       9
Support in Complex or Borderline Case           2
Total                                          36

Category: Counterfactual

                                            Count
Professional Confidence & Judgement             1
Validation and Justification of Decisions      13
Clarity and Specificity                         7
Emphasis on Individualized Decision Making      4
Usefulness and Efficiency                      16
Support in Complex or Borderline Case           7
Total                                          48

Category: Explanation Format

                                              Count
Preference for Combined Text and Visuals         10
Graphical Clarity and Ease of Interpretation      3
Textual Detail for Depth and Context              4
Interactive and Feedback-Enabled Systems          5
Total                                            22

Category: Actionability

                                           Count
Collaboration between AI and Humans            8
Validation and Justification of Decisions     10
Usefulness and Efficiency                      2
Scenario based explanations                   10
Total                                         30

In [13]:
import pandas as pd

# Ensure one-hot columns are numeric
df[one_hot_cols] = df[one_hot_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

# Loop through each Category - L1
for category in df['Category - L1'].unique():
    # Filter rows for the category
    cat_df = df[df['Category - L1'] == category].copy()
    
    # Keep only one-hot columns with any 1s in this category
    cat_one_hot_cols = cat_df[one_hot_cols].sum()
    cat_one_hot_cols = cat_one_hot_cols[cat_one_hot_cols > 0].index.tolist()
    
    if not cat_one_hot_cols:  # skip if no one-hot columns have values
        continue
    
    # Select relevant columns
    cat_table = cat_df[['Topic Quote', 'Quote Number', 'Participant Number'] + cat_one_hot_cols].copy()
    
    # Convert Quote Number and Participant Number to nullable integers
    cat_table['Quote Number'] = cat_table['Quote Number'].astype('Int64')
    cat_table['Participant Number'] = cat_table['Participant Number'].astype('Int64')
    
    # Add totals row for one-hot columns
    totals = pd.DataFrame(cat_table[cat_one_hot_cols].sum()).T
    totals['Topic Quote'] = 'Total'
    totals['Quote Number'] = pd.NA
    totals['Participant Number'] = pd.NA
    
    # Reorder columns to match
    totals = totals[cat_table.columns]
    
    # Append totals row
    cat_table = pd.concat([cat_table, totals], ignore_index=True)
    
    # Display the table with formatting:
    # - Topic Quote: left-aligned
    # - Numbers and one-hot columns: right-aligned
    print(f"\nCategory: {category}")
    display(
        cat_table.style.set_properties(subset=['Topic Quote'], **{'text-align': 'left'})
                  .set_properties(subset=cat_table.columns[1:], **{'text-align': 'right'})
                  .hide(axis="index")
    )

Category: Human Oversight Control

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Risks & Concerns

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Technical Elements

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Regulatory & Complaince

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Factual Explaination

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Semi Factual

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Counterfactual

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Explanation Format

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

Category: Actionability

/tmp/ipykernel_31417/3480308812.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cat_table = pd.concat([cat_table, totals], ignore_index=True)

In [14]:
import pandas as pd

# Assuming your final DataFrame is called df
output_file = "cleaned_underwriter_final.xlsx"

# Export to Excel
df.to_excel(output_file, index=False)

print(f"Data exported successfully to {output_file}")

Data exported successfully to cleaned_underwriter_final.xlsx